### ISSUE TITLE
Save Code.

### ISSUE THREAD

**Issue by hansputera** [codeonline-io/codeonline-community#11]
**Question**
I have finished my project on codeonline.io, but i haven't save code to GitHub. Can i get my code, and save it to GitHub? Because, loading is too long.

**Comment by steven166** [comment]
You can use git to push your code to GIthub.

**Comment by hansputera** [comment]
But, code.codeonline.io loading is too long. So, i can't use git.

**Comment by steven166** [comment]
There was an issue with your workspace, could you try it again?

**Comment by hansputera** [comment]
i was try it, but loading is too long. I want save my code on GitHub.

**Comment by steven166** [comment]
Could you please try again?

**Comment by hansputera** [comment]
Same

**Comment by steven166** [comment]
When I check the logs, your last active session was yesterday. Therefor it seems that something went wrong between your browser and our platform. 

What browser are you using? And could you check the developer console to see if there are errors or failed requests occurring?
