### ISSUE TITLE
[Bug] Not Loading To Editor

### ISSUE THREAD

**Issue by praveeno** [codeonline-io/codeonline-community#2]
**Describe the bug**
![image](https://user-images.githubusercontent.com/19618730/84594073-57725380-ae6d-11ea-95ed-dd5290fc92f6.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubantu 20
 - Browser [e.g. chrome, safari] chrome
it is not loading for me
**Additional context**

**Comment by steven166** [comment]
Thanks for reporting this bug. This is currently an open concurrency issue when your workspace is shutting down and wants to startup at the same time. I've checked your workspace and it should be okay now. 

We're currently working on this issue, will let you know when it is fixed.

**Comment by praveeno** [comment]
ok, also is codeonline BE is open source ?

**Comment by steven166** [comment]
vscode and code-server are both open source, but the schedular and proxy are not at this moment.

**Comment by steven166** [comment]
Thanks for you patient. A fix for this issue has been implemented and is live now.
