### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by eychamba** [codeonline-io/codeonline-community#6]
**Running Angular Project**

**I am getting error with angular project**

Hi, I am trying to run an angular project, but I am getting this message 

GET https://code.codeonline.io/polyfills.js net::ERR_ABORTED 404

the url that I use is https://code.codeonline.io/proxy/4200/

I am doing something wrong ?

**Comment by steven166** [comment]
I think you should set the basehref in Angular to `/proxy/4200`.
See also: https://angular.io/guide/router#base-href
