### ISSUE TITLE
Is Loading

### ISSUE THREAD

**Issue by eychamba** [codeonline-io/codeonline-community#7]
I was trying to test but suddenly it doesn't get past this sight

![notLoading](https://user-images.githubusercontent.com/3943062/96387533-6133fc80-1168-11eb-8e84-ce9f666752a2.png)

**Comment by steven166** [comment]
Hi @eychamba,
I've checked the metrics of your workspace and it seems that the cpu of your workspace got overloaded, which caused it to become unavailable. 
It also seems that the autorepair didn't kick in to restart your workspace. Will look into that.

Btw, if you require more cpu resources, you could consider upgrading to a [higher plan](https://www.codeonline.io/pricing.html).
