### ISSUE TITLE
[Question] Why is there no credit to the team who actually made the IDE?

### ISSUE THREAD

**Issue by Merith-TK** [codeonline-io/codeonline-community#9]
**Question**
So i noticed that what you guys are saying is "VSCode", is actually just code-server, a almost SEVERELY outdated version at that.
I self host an instance on my LAN which is what instantly told me this was `code-server`

This is the Version Info freely accessable at
![image](https://user-images.githubusercontent.com/10422110/98470795-fab96180-219c-11eb-8e73-f13c1ab5240c.png)

CodeOnline
```
code-server: v3.5.0
 VS Code: v1.48.2
Commit: 32d0a17b9609adc51ef22b8fcc229ea3a8c917e9
Date: 2020-09-07T20:44:41Z
```

My up to date server
```
code-server: v3.6.1
 VS Code: v1.50.0
Commit: 62735da69466a444561ab9b1115dc7c4d496d455
Date: 2020-10-23T20:39:50Z
```
https://github.com/cdr/code-server

And i have looked and see no reference stating that you are giving any form of credit to the people who made the software, and are instead advertising it as if it was an official product from Microsoft that you guys are using. 

And taken directly from 
https://www.codeonline.io/docs/#/?id=what-is-this 
>CodeOnline is an online IDE based on Visual Studio Code. While the frontend of the IDE is running in your browser for fast interfactions, it connects to a powerful external Linux backend which is running in the Cloud. So that you can access your workspace on any device, anywhere and always have the power, speed and reliablity of Cloud Computing.

You guys appear to be making it seem as if it is your own software, when it is not
Yes i am aware there is a fork on your guys github here, but that was last updated back in MARCH,

**Comment by steven166** [comment]
Hi there,
Thanks for reaching out regarding your concerns. 

CodeOnline is indeed based on 2 opensource projects: Code OSS and code-server. We reference them on this [page](https://www.codeonline.io/about.html). 

At the time of writing, CodeOnline is only 1 minor version behind the upstream (from september). After a new version is released, we need some time to test and ensure it is working flawless on our infrastructure. That is part of the service we offer. Therefor it is not always possible to run the latest version.

**Comment by Merith-TK** [comment]
Alright, Thanks for clearing things up, since Version 3 it has been much easier to update things depending on how you are running it.

I noticed with htop you are using the node method of running the program. Why dont you use the release tarballs? They remove one more dependency that you have to worry about testing it against, also could save some space on your servers

**Comment by steven166** [comment]
Thanks for the advise. Unfortunately we're require some customizations on top of code-server and vscode, therefor we cannot use their tarballs directly.

**Comment by Merith-TK** [comment]
What kind of customization? The source code repo here is out of date by 9 months

**Comment by steven166** [comment]
Some minor ajustments to integrate better with our infrastructure. It is on our list to  push them to the opensource repo.

**Comment by Merith-TK** [comment]
Ah, neat. Alright
